sources:
  - name: NasaNEO
    handler:
      jsonSchema:
        endpoint: "https://api.nasa.gov/neo/rest/v1/feed"
        operations:
          - type: Query
            field: nasaNeoFeed
            path: "?start_date={args.startDate}&end_date={args.endDate}&api_key=DEMO_KEY"
            method: GET
            argTypeMap:
              startDate: String
              endDate: String
            responseSchema: ./data/nasa-neo-sample.json
